print("안녕하세요! 컴퓨터공학전공 19학번 한다현입니다.")
print("파이썬 여름 계절 수업을 듣게되었는데 잘부탁드려요~")
print("방학동안 열심히 해보겠습니다!")
print("")
print("Hello World!")
print(2*3)
print(2+3)
print(2-3)
print(2/3)
print()
print("cat" "dog frog")
print("cat"+"dog frog")
print()
print("결과값은",3*5,"입니다.")
print("life","is","too short")
print("안녕하세요"*10)
number=input("숫자를 입력하세요: ")
print(number)
